//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_GDFW : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean UserInterfaceAppear
        {
            get
            {
                return SteamVR_Actions.gDFW_UserInterfaceAppear;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveUserInterfaceForward
        {
            get
            {
                return SteamVR_Actions.gDFW_MoveUserInterfaceForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveUserInterfaceBackward
        {
            get
            {
                return SteamVR_Actions.gDFW_MoveUserInterfaceBackward;
            }
        }
    }
}
